---
- hosts: localhost
  vars:
    product: waveserverai
    ansible_collection_root: /home/{{ansible_user_id}}/src/ansible_collections
    modules:
      - directory: ciena-waveserver-system
        resource: system
      # - ciena-waveserver-xcvr
      # - ciena-waveserver-ptp
      # - ciena-waveserver-port
    overwrite: true
  tasks:
    - name: Remove directory
      ansible.builtin.file:
        path: build/waveserverai
        state: absent
    - name: Run execution
      ansible.builtin.include_tasks: playbook_tasks.yml
      with_items: "{{ modules }}"
