---
- hosts: localhost
  vars:
    product: waveserverai
    ansible_collection_root: /home/{{ansible_user_id}}/src/ansible_collections
    modules:
      - directory: ciena-waveserver-system
        resource: system
      - directory: ciena-waveserver-xcvr
        resource: xcvrs
      - directory: ciena-waveserver-ptp
        resource: ptps
      - directory: ciena-waveserver-port
        resource: ports
    overwrite: true
  tasks:
    - name: Remove directory
      ansible.builtin.file:
        path: build/{{ product }}
        state: absent
    - name: Run execution
      ansible.builtin.include_tasks: playbook_tasks.yml
      with_items: "{{ modules }}"
