= Resource module builder using Yang models

== Overview

This builder uses a yang definition to generate a resource module for the Ciena collections.

Generates modules for:

* Waveserver Ai
* SAOS 10
* Waveserver 5
* RLS

== Usage

=== Download yangs

[source,bash]
----
# update inventory.yml with the device type you are working on
ansible-playbook yang_get.yml
----

=== Create the module type directory and files

The playbooks in this project generate modules for Ciena collections using the resource module builder.

Add the module type to the device type directory. Create the input.yml file and merged_example.txt file.

.Diagram of Directory Structure
[source]
----
models/
|-- saos10/
|   |-- classifiers/
|   |   |-- input.yml
|   |   `-- merged_example.txt
|   |-- fds/
|   |   |-- input.yml
|   |   `-- merged_example.txt
|   `-- fps/
|   |   |-- input.yml
|   |   `-- merged_example.txt
`-- waveserver5/
    |-- aaa/
    |   |-- input.yml
    |   `-- merged_example.txt
    `-- integration/
        |-- input.yml
        `-- merged_example.txt
----

The input.yml file is used to generate the model.yml file. It specifies the namespace, module name, and if any nested suboptions from the yang are required.

[source,yaml]
---
include::models/saos10/classifiers/input.yml[]
---

=== Generate the model.yml file

This step uses a custom pyang translator to generate the model.yml file. The input.yml and the yang file are used to generate the model.yml file.

[source,bash]
----
#!/bin/bash
export PYANG_PLUGINPATH=~/src/resource_module_builder/pyang-plugin
# SAOS10
pyang -f ansible -p yangs/saos10 -i models/saos10/classifiers/input.yml yangs/saos10/ciena-mef-classifier.yang > models/saos10/classifiers/model.yml
pyang -f ansible -p yangs/saos10 -i models/saos10/fds/input.yml yangs/saos10/ciena-mef-fd.yang > models/saos10/fds/model.yml
pyang -f ansible -p yangs/saos10 -i models/saos10/fps/input.yml yangs/saos10/ciena-mef-fp.yang > models/saos10/fps/model.yml
----

=== Generate the module code

This step is roughly the traditional way to generate the module code. It uses the model.yml file to generate the module code. However, it uses a newer schema for the model generation.

[NOTE]
====
The module generation assumes that the ansible collections are installed in the following directory:
/home/{{ansible_user_id}}/src/ansible_collections
====

[source,bash]
----
pip install git+https://github.com/ansible-network/collection_prep.git

# Generate the module code
ansible-playbook generate_saos10.yml
ansible-playbook generate_waveserver5.yml
----
