xml_namespace: urn:ciena:params:xml:ns:yang:ciena-ws:ciena-waveserver-application-auto-fiber-discovery
network_os: waveserverai
potential_modules:
  auto_fiber_discovery:
    description: Auto Fiber Discovery configuration data.
    type: dict
    suboptions:
      state:
        description: Configuration data for Auto Fiber Discovery
        type: dict
        suboptions:
          admin_state:
            description: Auto Fiber Discovery Admin State
            type: str
            required: false
            choices:
            - disabled
            - enabled
