xml_namespace: urn:ciena:params:xml:ns:yang:ciena-ws:ciena-waveserver-application-otdr
network_os: waveserverai
potential_modules:
  waveserver_application_otdr:
    description: Optical Time Domain Reflectometer (OTDR) configuration data.
    type: dict
    suboptions:
      profile:
        description: Configuration data for the OTDR Profiles
        type: list
        elements: dict
        suboptions:
          profile_id:
            description: 'Unique ID of an OTDR Profile; <1..16>, office, short, long. Only profile-ids <2..16> can be created/deleted. (Key for
              list: profile)'
            type: str
            required: true
          description:
            description: A description of the OTDR Profile.
            type: str
            required: false
          distance:
            description: Distance in meters Range <10..128000>
            type: int
            required: false
          measure_time:
            description: Measure time in seconds Range <1..180>
            type: int
            required: false
          pulse_width:
            description: Pulse width in nano-seconds Range <10|30|100|300|1000|3000|10000|20000>
            type: int
            required: false
        key: profile-id
