GENERATOR_VERSION: '2.0'
NETWORK_OS: waveserverai
RESOURCE: waveserver-configuration
XML_NAMESPACE: urn:ciena:params:xml:ns:yang:ciena-ws:ciena-waveserver-configuration
XML_ROOT_KEY: waveserver-configuration
XML_ITEMS: null
XML_ITEMS_KEY: null
ANSIBLE_METADATA:
  metadata_version: '2.0'
  status:
  - preview
  supported_by: network
COPYRIGHT: Copyright 2025 Ciena
DOCUMENTATION:
  module: waveserverai_waveserver_configuration
  short_description: Manage waveserver_configuration on Ciena waveserverai devices.
  description: Waveserver Configuration; configuration data and operational data.
  author: Ciena
  options:
    config:
      description: Waveserver Configuration; zero touch provisioning data
      type: dict
      suboptions:
        state:
          description: ZTP configuration and operational data.
          type: dict
          suboptions:
            admin_state:
              description: Whether the ZTP admin state is enabled or disabled. When ZTP is disabled, DHCP bootfile requests will be ignored.
              type: str
              required: false
              choices:
              - disabled
              - enabled
    state:
      description: The state of the configuration after module completion.
      type: str
      choices:
      - merged
      - deleted
      default: merged
EXAMPLES:
- merged_example_01.txt
- deleted_example_01.txt
notes:
- This module requires the netconf system service be enabled on the remote device being managed.
- This module works with connection C(netconf)
requirements:
- ncclient (>=v0.6.4)
