GENERATOR_VERSION: '2.0'
NETWORK_OS: waveserverai
RESOURCE: auto-fiber-discovery
XML_NAMESPACE: urn:ciena:params:xml:ns:yang:ciena-ws:ciena-waveserver-application-auto-fiber-discovery
XML_ROOT_KEY: auto-fiber-discovery
XML_ITEMS: null
XML_ITEMS_KEY: null
ANSIBLE_METADATA:
  metadata_version: '2.0'
  status:
  - preview
  supported_by: network
COPYRIGHT: Copyright 2025 Ciena
DOCUMENTATION:
  module: waveserverai_auto_fiber_discovery
  short_description: Manage auto_fiber_discovery on Ciena waveserverai devices.
  description: Auto Fiber Discovery configuration data.
  author: Ciena
  options:
    config:
      description: Configuration data for Auto Fiber Discovery
      type: dict
      suboptions:
        admin_state:
          description: Auto Fiber Discovery Admin State
          type: str
          required: false
          choices:
          - disabled
          - enabled
    state:
      description: The state of the configuration after module completion.
      type: str
      choices:
      - merged
      - deleted
      default: merged
EXAMPLES:
- merged_example_01.txt
- deleted_example_01.txt
notes:
- This module requires the netconf system service be enabled on the remote device being managed.
- This module works with connection C(netconf)
requirements:
- ncclient (>=v0.6.4)
