waveserver_application_otdr:
  description: Optical Time Domain Reflectometer (OTDR) configuration data.
  suboptions:
    profile:
      description: Configuration data for the OTDR Profiles
      elements: dict
      suboptions:
        description:
          description: A description of the OTDR Profile.
          required: false
          type: str
        distance:
          description: Distance in meters Range <10..128000>
          required: false
          type: int
        measure_time:
          description: Measure time in seconds Range <1..180>
          required: false
          type: int
        profile_id:
          description: 'Unique ID of an OTDR Profile; <1..16>, office, short, long.
            Only profile-ids <2..16> can be created/deleted. (Key for list: profile)'
          required: true
          type: str
        pulse_width:
          description: Pulse width in nano-seconds Range <10|30|100|300|1000|3000|10000|20000>
          required: false
          type: int
      type: list
  type: dict
