waveserver_configuration:
  description: Waveserver Configuration; configuration data and operational data.
  suboptions:
    ztp:
      description: Waveserver Configuration; zero touch provisioning data
      suboptions:
        state:
          description: ZTP configuration and operational data.
          suboptions:
            admin_state:
              choices:
              - disabled
              - enabled
              description: Whether the ZTP admin state is enabled or disabled. When
                ZTP is disabled, DHCP bootfile requests will be ignored.
              required: false
              type: str
          type: dict
      type: dict
  type: dict
