auto_fiber_discovery:
  description: Auto Fiber Discovery configuration data.
  suboptions:
    state:
      description: Configuration data for Auto Fiber Discovery
      suboptions:
        admin_state:
          choices:
          - disabled
          - enabled
          description: Auto Fiber Discovery Admin State
          required: false
          type: str
      type: dict
  type: dict
