- name: Ensure 'rm_dest' variable is set (see README.md)
  ansible.builtin.assert:
    that: rm_dest is defined

- name: Ensure 'structure' variable is set and one of 'role' or 'collection' (see README.md)
  ansible.builtin.assert:
    that: structure is defined and structure in ['role', 'collection']

- name: Ensure the 'model' variable is set
  ansible.builtin.assert:
    that: model is defined

- name: Include the model vars
  ansible.builtin.include_vars:
    file: "{{ model }}"
    name: rm

- name: "Create directory structure: {{ structure }}"
  ansible.builtin.assert:
    path: "{{ rm_dest }}/{{ item }}"
    state: directory
  with_items: "{{ directories[structure] }}"

- name: Ensure the 'collection_org' is set when 'structure' is set to collection
  ansible.builtin.assert:
    that: collection_org is defined
  when: structure == 'collection'

- name: Ensure the 'collection_name' is set when 'structure' is set to collection
  ansible.builtin.assert:
    that: collection_name is defined
  when: structure == 'collection'
